##Validating HH
table(ifelse(is.na(chh$start_time),chh$interview__key,NA))
table(ifelse(chh$gps__Latitude < 1, chh$interview__key,NA))
table(ifelse(chh$gps__Longitude < 1, chh$interview__key,NA))
table(ifelse(chh$gps__Accuracy < 1, chh$interview__key,NA))
table(ifelse(is.na(chh$phc), chh$interview__key,NA))
table(ifelse(is.na(chh$sc), chh$interview__key,NA))
table(ifelse(is.na(chh$village), chh$interview__key,NA))
table(ifelse(chh$ic_understood != 1, chh$interview__key,NA))
table(ifelse(chh$ic_questions != 2, chh$interview__key,NA))
table(ifelse(chh$ic_consent != 1, chh$interview__key,NA))
table(ifelse(chh$caste < 0, chh$interview__key,NA))
table(ifelse(is.na(chh$ration_own) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(chh$ration_own < 0, chh$interview__key,NA))
table(ifelse(is.na(chh$ration_type) & chh$ration_own == 1, chh$interview__key,NA))
table(ifelse(chh$ration_type < 0 & chh$ration_own == 1, chh$interview__key,NA))
table(ifelse(is.na(chh$caste) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(chh$caste < 0, chh$interview__key,NA))
table(ifelse(chh$living_since < 0, chh$interview__key,NA))
table(ifelse(is.na(chh$living_since) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(chh$insure < 0, chh$interview__key,NA))
table(ifelse(is.na(chh$insure) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(is.na(chh$insure_type__1) & chh$insure == 1, chh$interview__key,NA))
table(ifelse(is.na(chh$insure_type__2) & chh$insure == 1, chh$interview__key,NA))
table(ifelse(is.na(chh$insure_type__3) & chh$insure == 1, chh$interview__key,NA))
table(ifelse(is.na(chh$insure_type__4) & chh$insure == 1, chh$interview__key,NA))
table(ifelse(chh$insure_type__1 < 0, chh$interview__key,NA))
table(ifelse(chh$insure_type__2 < 0, chh$interview__key,NA))
table(ifelse(chh$insure_type__3 < 0, chh$interview__key,NA))
table(ifelse(chh$insure_type__4 < 0, chh$interview__key,NA))
table(ifelse(chh$insure_other != "", chh$interview__key, NA))
table(ifelse(chh$fmember_no <= 0, chh$interview__key,NA))
table(ifelse(is.na(chh$fmember_no) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(is.na(chh$wi_drink_water) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(chh$wi_drink_water <= 0, chh$interview__key,NA))
table(ifelse(is.na(chh$wi_toilet) & chh$locked == 2, chh$interview__key,NA))
table(ifelse(chh$wi_toilet <= 0, chh$interview__key,NA))
table(ifelse(chh$wi_drink_water_other != "" & chh$interview__status == 120, chh$interview__key, NA))
#table(ifelse(is.na(chh$wi_drink_water_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_drink_water_other)
table(ifelse(chh$wi_toilet_other != "", chh$interview__key, NA))
#table(ifelse(is.na(chh$wi_toilet_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_toilet_other)
table(ifelse(chh$wi_electricity < 0, chh$interview__key,NA))
table(ifelse(chh$wi_mattress < 0, chh$interview__key,NA))
table(ifelse(chh$wi_cooker < 0, chh$interview__key,NA))
table(ifelse(chh$wi_chair < 0, chh$interview__key,NA))
table(ifelse(chh$wi_bed < 0, chh$interview__key,NA))
table(ifelse(chh$wi_table < 0, chh$interview__key,NA))
table(ifelse(chh$wi_fan < 0, chh$interview__key,NA))
table(ifelse(chh$wi_radio < 0, chh$interview__key,NA))
table(ifelse(chh$wi_bwtv < 0, chh$interview__key,NA))
table(ifelse(chh$wi_coltv < 0, chh$interview__key,NA))
table(ifelse(chh$wi_sewingmach < 0, chh$interview__key,NA))
table(ifelse(chh$wi_mob_phone < 0, chh$interview__key,NA))
table(ifelse(chh$wi_ll_phone < 0, chh$interview__key,NA))
table(ifelse(chh$wi_internet < 0, chh$interview__key,NA))
table(ifelse(chh$wi_computer < 0, chh$interview__key,NA))
table(ifelse(chh$wi_refrigerator < 0, chh$interview__key,NA))
table(ifelse(chh$wi_ac < 0, chh$interview__key,NA))
table(ifelse(chh$wi_washmach < 0, chh$interview__key,NA))
table(ifelse(chh$wi_clock < 0, chh$interview__key,NA))
table(ifelse(chh$wi_bicycle < 0, chh$interview__key,NA))
table(ifelse(chh$wi_motorcycle < 0, chh$interview__key,NA))
table(ifelse(chh$wi_cart < 0, chh$interview__key,NA))
table(ifelse(chh$wi_car < 0, chh$interview__key,NA))
table(ifelse(chh$wi_pump < 0, chh$interview__key,NA))
table(ifelse(chh$wi_thresher < 0, chh$interview__key,NA))
table(ifelse(chh$wi_tractor < 0, chh$interview__key,NA))
table(ifelse(chh$wi_cooking_fuel < 0, chh$interview__key,NA))
table(ifelse(chh$wi_cooking_fuel_other != "", chh$interview__key, NA))
#table(ifelse(is.na(chh$wi_cooking_fuel_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_cooking_fuel_other)
table(ifelse(chh$wi_floor < 0, chh$interview__key,NA))
table(ifelse(chh$wi_roof < 0, chh$interview__key,NA))
table(ifelse(chh$wi_wall < 0, chh$interview__key,NA))

table(ifelse(chh$wi_floor_other != "" & chh$interview__status == 120, chh$interview__key, NA))
#table(ifelse(is.na(chh$wi_floor_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_floor_other)

table(ifelse(chh$wi_roof_other != "", chh$interview__key, NA))
#table(ifelse(is.na(chh$wi_roof_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_roof_other)

table(ifelse(chh$wi_wall_other != "", chh$interview__key, NA))
#table(ifelse(chh$wi_wall_other != "", chh$interview__status, NA))
#table(ifelse(is.na(chh$wi_wall_other) & chh$locked == 2, chh$interview__key,NA))
table(chh$wi_wall_other)

table(ifelse(chh$wi_account < 0, chh$interview__key,NA))
table(chh$wi_account)
table(ifelse(chh$wi_loan < 0, chh$interview__key,NA))
table(chh$wi_loan)
table(ifelse(chh$wi_loan_type__1 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__2 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__3 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__4 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__5 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__6 < 0, chh$interview__key,NA))
table(ifelse(chh$wi_loan_type__7 < 0, chh$interview__key,NA))
table(chh$wi_loan_type__1)
table(chh$wi_loan_type__2)
table(chh$wi_loan_type__3)
table(chh$wi_loan_type__4)
table(chh$wi_loan_type__5)
table(chh$wi_loan_type__6)
table(chh$wi_loan_type__7)
table(ifelse(chh$locked < 0, chh$interview__key,NA))
table(chh$locked)
table(ifelse(is.na(chh$hoh_name) & chh$locked == 1, chh$interview__key,NA))
table(ifelse(chh$hoh_name == "" & chh$locked == 1, chh$interview__key,NA))

#CDAT
table(ifelse(cind$newage > 100, cind$interview__key,NA))
table(ifelse(cind$gender == "-999999999", cind$interview__key,NA))
table(ifelse(cind$birth_know < 0, cind$interview__key,NA))
table(cind$birth_know)
table(ifelse(cind$dob > 0 & cind$birth_know == 2, cind$interview__key,NA))
table(ifelse(cind$age_d > 0 & cind$birth_know == 1, cind$interview__key,NA))
table(ifelse(cind$age > 0 & cind$birth_know == 2, cind$interview__key,NA))

